case_details:
  case_name: "local-case"
  case_description: "Run via local enqueuer/worker"

redis:
  host: "127.0.0.1"
  port: 6379
  job_queue: "forceps:job_queue"
  results_queue: "forceps:results_queue"

data:
  input_dir: "/Users/Shared/Projects/2017"
  output_dir: "/Users/Shared/Projects/foreceps/output_index"

models:
  onnx_dir: "/Users/Shared/Projects/foreceps/models/onnx"

performance:
  worker:
    batch_size: 64  # Increased batch size for better GPU utilization
    max_workers: 16  # More parallel workers
  enqueuer:
    job_batch_size: 1024  # Larger job batches for better throughput
    scan_max_workers: 32  # More parallel scanning
  faiss:
    use_pca: true
    pca_dim: 384
    ivf_nlist: 64
    pq_m: 32
    train_samples: 1000
    add_batch: 100

hashing:
  - "sha256"
  - "perceptual"

features:
  enable_captions: false  # Disabled to reduce cost and complexity

